### PR TITLE
add Base paymaster actions

### PR DESCRIPTION
**Pull request by lukasrosario**
- add actions for [Base's paymaster](https://github.com/base-org/paymaster)

### CODE REVIEW

**Comment by lukasrosario** [comment]
@plusminushalf @kristofgazso hey! wondering if there's anything else needed to get this in? happy to make any edits.

**Comment by plusminushalf** [comment]
Hey will check this in a day or two

**Comment by lukasrosario** [comment]
cool thank you both for getting back to me, lmk if there's anything I can do to help

**Review by Dropkick13 — APPROVED** [review]

**Comment by plusminushalf** [comment]
Hey @lukasrosario is this still relevant? Given coinbase paymaster service is `Eip7677` compatible?

**Pull request closed without merging**
